# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-05 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='carbrand.BaseModel')),
                ('name_ch', models.CharField(max_length=64)),
                ('name_en', models.CharField(max_length=128)),
                ('image_url', models.CharField(blank=True, max_length=1024)),
                ('country', models.CharField(max_length=128)),
            ],
            bases=('carbrand.basemodel',),
        ),
        migrations.CreateModel(
            name='CarBrandDetail',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='carbrand.BaseModel')),
                ('introducetion', models.TextField()),
                ('office_website', models.CharField(max_length=512)),
                ('carbrand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbrand.CarBrand')),
            ],
            bases=('carbrand.basemodel',),
        ),
        migrations.CreateModel(
            name='ClassicModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='carbrand.BaseModel')),
                ('image_url', models.CharField(blank=True, max_length=1024)),
                ('guidence_price', models.CharField(max_length=128)),
                ('carbrand_det', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbrand.CarBrandDetail')),
            ],
            bases=('carbrand.basemodel',),
        ),
    ]
