# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-15 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('carbrand_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_cn', models.CharField(max_length=64)),
                ('name_en', models.CharField(blank=True, max_length=128, null=True)),
                ('img', models.CharField(blank=True, max_length=1024, null=True)),
                ('introduction', models.TextField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=512, null=True)),
                ('ranking', models.IntegerField()),
                ('level', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.IntegerField(primary_key=True, serialize=False)),
                ('country_name_cn', models.CharField(blank=True, max_length=128, null=True)),
                ('country_name_en', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('image_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('guidence_price', models.CharField(max_length=128)),
                ('carbrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbrand.CarBrand')),
            ],
        ),
        migrations.AddField(
            model_name='carbrand',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='carbrand.Country'),
        ),
    ]
